name: PR Checks
on: [pull_request]

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-commit-lint
      cancel-in-progress: true
    name: Commitlint
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v5
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - name: lint
        run: |
          npm ci --workspaces false
          npm run lint:ci
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-pr-build
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]
    name: Build & Test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & Build
        run: |
          npm ci
      - name: Test
        run: |
          npm run test:all -- --skip-nx-cache
      - name: Publint
        run: |
          npm run publint:all

  tsdoc-check:
    runs-on: ubuntu-latest
    name: Check TSDoc Links
    concurrency:
      group: ${{ github.ref }}-tsdoc-check
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Check TSDoc Links
        run: npx tsdoc-link-check --patterns packages/**
