name: PR Previews

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    paths:
      - "packages/**"
      - "examples/finefoods-antd/**"
      - "examples/finefoods-material-ui/**"
      - "examples/finefoods-client/**"

jobs:
  antd-fine-foods:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-pr-antd-fine-foods
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    name: Fine Foods Antd

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm ci --workspaces false
          npm install -w finefoods-antd
          npm run build -- --scope finefoods-antd
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./examples/finefoods-antd/dist"
          github-token: ${{ secrets.PANKOD_BOT_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          alias: deploy-preview-antd-${{ github.event.number }}
          enable-pull-request-comment: false
          overwrites-pull-request-comment: false
          github-deployment-environment: "deploy-preview-antd-${{ github.event.number }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10
  mui-fine-foods:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-pr-mui-fine-foods
      cancel-in-progress: true
    strategy:
      matrix:
        node-version: [18.x]

    name: Fine Foods Material UI

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm ci --workspaces false
          npm install -w finefoods-material-ui
          npm run build -- --scope finefoods-material-ui
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./examples/finefoods-material-ui/dist"
          github-token: ${{ secrets.PANKOD_BOT_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          alias: deploy-preview-mui-${{ github.event.number }}
          enable-pull-request-comment: false
          overwrites-pull-request-comment: false
          github-deployment-environment: "deploy-preview-mui-${{ github.event.number }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10
